baseURL = "https://gil.fyi/"
languageCode = "en-us"
title = "gil.fyi"
theme = "hugo-classic"
enableEmoji = true
footnotereturnlinkcontents = "â†©"
relativeURLs = true

[permalinks]
    post = "/posts/:year/:month/:day/:slug/"

[[menu.main]]
    name = "ğŸ’¼"
    url = "/professional"
    weight = 1

[[menu.main]]
    name = "ğŸ“š"
    url = "/readings"
    weight = 2

[[menu.main]]
    name = "âœï¸"
    url = "/posts"
    weight = 3

[[menu.main]]
    name = "ğŸ—„ï¸"
    url = "/categories/"
    weight = 4

[[menu.main]]
    name = "ğŸ·ï¸"
    url = "/tags/"
    weight = 5

[[menu.feed]]
    name = "rss"
    url = "/index.xml"

[params]
    footer = """\
    built using [hugo](https://gohugo.io) | deployed on [firebase](https://firebase.google.com/docs/hosting) | source code [here](https://github.com/ggiill/website)\n\n\
    ğŸ”— [github](https://github.com/ggiill) | [linkedin](https://www.linkedin.com/in/gilturetsky/) | [keybase](https://keybase.io/gturetsky) | [twitter](https://twitter.com/_ggiill_) | [email](mailto:public@gil.fyi) ğŸ”—"""
    custom_css = ["css/theme-override.css"]

[markup]
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = "manni"
        tabWidth = 4
    [markup.goldmark.renderer]
        unsafe = true
